#!/bin/bash

PKG_NAME="CPUTemp"
TARGET_DIR="/var/packages/${PKG_NAME}/target"
BIN_DIR="${TARGET_DIR}/bin"

# Get DSM major version
dsm=$(/usr/syno/bin/synogetkeyvalue /etc.defaults/VERSION majorversion)
if [[ $dsm -ge 7 ]]; then
    VAR_DIR="/var/packages/${PKG_NAME}/var"
else
    VAR_DIR="/var/packages/${PKG_NAME}/etc"
fi

log_message() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" >> "${VAR_DIR}/install.log" 2>/dev/null || true
}

exit 0
